### ISSUE TITLE
Bug: "No Directionality widget found" when `KeyboardEmojiPickerWrapper` placed outside of `MaterialApp`

### ISSUE THREAD

**Issue by Shawn-sudo** [f-person/keyboard_emoji_picker#1]
Hi, thanks for this wonderful package!

I realized that when I put `KeyboardEmojiPickerWrapper()` outside of `MaterialApp()`, Flutter throws an error saying that no Directionality widget is found:
<img src=https://github.com/f-person/keyboard_emoji_picker/assets/60294318/083ea92e-8b0c-42dd-9298-9562cc522982 width=200/>

The error message says the `alignment` property of `Stack()` widget used in `KeyboardEmojiPickerWrapper()` defaults to `.topStart`, which requires `Directionality()` widget to be in the parent widget tree.

When `KeyboardEmojiPickerWrapper()` is placed under `MaterialApp()`, it works fine because `MaterialApp()` contains `Directionality()` widget, but when it's placed outside of it, it doesn't work well

```
    return KeyboardEmojiPickerWrapper(//it's outside of MaterialApp -> throws the error
      child: MaterialApp(
        title: 'My App',
        home: MyHomePage(),
      ),
    );
```

I guess setting `alignment` of the `Stack()` widget in `KeyboardEmojiPickerWrapper()` to be `Alignment.center` solves it

**Comment by f-person** [comment]
Fixed by #2

**Comment by Shawn-sudo** [comment]
@f-person Oh wait my bad
That PR might not fix the problem fully
It says `UiKitView` also requires `Directionality` widget ancestor

<img src=https://github.com/f-person/keyboard_emoji_picker/assets/60294318/f06dc442-1e22-4840-9da8-70e3d2f75d48 width=200 />

**Comment by f-person** [comment]
Check 2fd9975 (or version 1.0.3)

**Comment by Shawn-sudo** [comment]
Oh
Yea using `Directionality.maybeOf(context)` seems to be a nice solution!
It works when I test it too

Thanks!

**Comment by f-person** [comment]
Awesome! Good luck with Atrable! 🪅

**Comment by Shawn-sudo** [comment]
lol ok
Good luck with your tech & music stuff too!
